spring:
  application.name: sample-spring-rabbitmq
  rabbitmq:
    cache:
      channel:
        size: 15


management.endpoints.web.exposure.include: "*"
management.endpoints.web.exposure.exclude:

non-durable:
  enabled: true
  producer.enabled: true
  consumer:
    enabled: true
    requeueRejectedMessages: false

durable:
  enabled: true
  producer.enabled: true
  consumer.enabled: true
