
logging:
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} [%t]  %clr(%-40.40logger{1}){cyan} %msg %n"
  level:
    com.pivotal.resilient: debug
    org:
      springframework:
        retry:
          support:
            RetryTemplate: debug
server:
  port: 8082
  
tradeService: default

spring:
  application:
    name: durable-consumer
  profiles:
    include:
      - management
      - cluster
  cloud:
    stream:
      bindings: # spring cloud stream binding configuration
        outboundTradeRequests:
          destination: trades
          producer:
            errorChannelEnabled: true # send failures are sent to an error channel for the destination
            requiredGroups:
              - trade-logger
      rabbit:
        bindings:
          outboundTradeRequests:
            producer:
              deliveryMode: PERSISTENT # default value. Here for completeness
              confirmAckChannel: trades.confirm # channel where to receive publish confirms
