
spring:
  cloud:
    stream:
      rabbit:
        bindings:
          durable-trade-logger-input:
            consumer:
              autoBindDlq: true
              republishToDlq: false  # default is true

