
spring:
  application:
    name: resilient-spring-rabbitmq
  rabbitmq:
    publisher-confirms: true
    publisher-returns: true
    requested-heartbeat: 0
    ssl:
      enabled: false
      validate-server-certificate: true
      verify-hostname: false
      #trust-store: "file:/tmp/docker-test/trust-store.p12"
      #trust-store-password: roboconf
      #trust-store-type: PKCS12

management:
  security:
    enabled: false
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
          - env
          - prometheus
          - beans


issues:
  useRabbitMQClusterAtStartup: false

durable:
  enabled: false
  producer:
    enabled: false
  consumer:
    enabled: false


no-message-loss:
  enabled: true
  queue-name: no-message-loss-q
  exchange-name: no-message-loss-e
  routing-key: no-message-loss-q
  synchronous-producer:
    enabled: false
  consumer:
    enabled: false



