
spring:
  application:
    name: resilient-spring-rabbitmq
  rabbitmq:
      requested-heartbeat: 0
      ssl:
        enabled: false
        validate-server-certificate: true
        verify-hostname: false
        #trust-store: "file:/tmp/docker-test/trust-store.p12"
        #trust-store-password: roboconf
        #trust-store-type: PKCS12

management:
  security:
    enabled: false
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
          - env
          - prometheus


issues:
  useRabbitMQClusterAtStartup: false

durable.producer.enabled: true
#non-durable.producer.enabled: false
