
logging:
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-40.40logger{1}){cyan} %msg %n"
  level:
    com.pivotal.resilient: debug

spring:
  application:
    name: transient-consumer
  profiles:
    include:
      - management
      - cluster
  cloud:
    stream:
      bindings: # spring cloud stream binding configuration
        trade-logger-input:
          destination: trades
          consumer:
            maxAttempts: 3  # default is 3
