
logging:
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-40.40logger{1}){cyan} %msg %n"
  level:
    com.pivotal.resilient: debug

spring:
  application:
    name: resilient-scs-rabbitmq
  profiles:
    include:
      - management
      - cluster
  cloud:
    stream:
      bindings: # spring cloud stream binding configuration
        outboundTradeRequests:
          destination: trades
        trade-logger-input:
          destination: trades
        durable-trade-logger-input:
          destination: trades
          group: trade-logger
      rabbit: # spring cloud stream rabbit binder configuration
        binder:
        # connection-name-prefix: hello  Cannot use it due to cycle issue during initialization
       
