
logging:
  level:
    com.pivotal.resilient: debug

spring:
  application:
    name: resilient-scs-rabbitmq
  profiles:
    include:
      - management
  cloud:
    stream:
      bindings:
        outboundTradeRequests:
          destination: trades
        inboundTradeRequests:
          destination: trades
