spring:
  application:
    name: resilient-skeleton-spring-rabbitmq

management:
  security:
    enabled: false
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
          - env




