
logging:
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-40.40logger{1}){cyan} %msg %n"
  level:
    com.pivotal.resilient: debug

spring:
  cloud:
    stream:
      bindings: # spring cloud stream binding configuration
        outboundTradeRequests:
          destination: trades
          producer:
            requiredGroups:
              - trade-logger

